# Generated by Django 4.1.5 on 2023-01-13 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['title', 'completed', 'description'],
            },
        ),
    ]
